name: Twee Autodeploy
description: Automatically build and host a twee project to github pages. Branches included! 
branding:
  icon: arrow-up-circle
  color: purple



  

on:
  push:
  workflow_call:
    inputs:
      github_token:
        description: Github access token
        required: true
    outputs:
      branch:
        description: Branch targetted by this run
        value: ${{ jobs.build.outputs.branch }}
  

jobs:
  build:
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT 
        id: extract_branch

      - name: Use Go 1.13
        uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.13.x

      - uses: jaxxstorm/action-install-gh-release@v1.12.0 
        with:
          repo: tmedwards/tweego
          chmod: 0775
      - run : tweego source -o index.html

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ inputs.github_token  }}
          publish_branch: gh-pages
          publish_dir: ./
          destination_dir: ${{ outputs.branch }}
